# Generated by Django 3.2.3 on 2021-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
